import type { NextPage } from 'next';
import Head from 'next/head';
import About from '../components/About';
import BackgroundAnimation from '../components/BackgroundAnimation';
import Footer from '../components/Footer';
import Hero from '../components/Hero';
import Navbar from '../components/Navbar';
import Project from '../components/Project';
import Skill from '../components/Skill';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Krunal Patel Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/avtar.png" />
      </Head>

      <Navbar />

      <div>
        <BackgroundAnimation />
        <Hero />
      </div>

      <About />

      <Skill />

      <Project />

      <Footer />
    </div>
  );
};

export default Home;
